# Numpy

In [1]:
import numpy as np
import sys

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0,.5,1,1.5,2])

In [8]:
a[0],a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1:3]

array([2, 3])

In [12]:
a[1:-1]

array([2, 3])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0,2,-1]]

array([0., 1., 2.])

# Array Types

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [30]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [31]:
c = np.array(['a', 'b', 'c'])

In [32]:
c.dtype

dtype('<U1')

In [33]:
d = np.array([{'a':1},sys])

In [34]:
d.dtype

dtype('O')

# Dimensions and shapes

In [36]:
A = np.array([[1,2,3],[4,5,6]])

In [37]:
A.shape

(2, 3)

In [38]:
A.ndim

2

In [39]:
A.size

6

In [40]:
B = np.array([[[12,11,10],[9,8,7]],[[6,5,4],[3,2,1]]])

In [41]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [42]:
B.shape

(2, 2, 3)

In [43]:
B.ndim

3

In [45]:
B.size

12

In [47]:
C = np.array([[[12,11,10],[9,8,7]],[[6,5,4]]])

C:\Users\buysa\AppData\Local\Temp\ipykernel_15852\2114691219.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([[[12,11,10],[9,8,7]],[[6,5,4]]])


In [48]:
C.dtype

dtype('O')

In [49]:
C.shape

(2,)

In [50]:
d.size

2

In [51]:
type(C[0])

list

# Indexing and Slicing of Matrices

In [52]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
A[1]

array([4, 5, 6])

In [54]:
A[1][0]

4

In [55]:
A[1, 0]

4

In [56]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [59]:
A[:2,2:]

array([[3],
       [6]])

In [60]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
A[1] = np.array([10,10,10])

In [62]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [63]:
A[2] = 99

In [64]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [65]:
a = np.array([1,2,3,4])

In [66]:
a.sum()

10

In [67]:
a.mean()

2.5

In [68]:
a.std()

1.118033988749895

In [69]:
a.var()

1.25

In [70]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
A.sum()

45

In [72]:
A.mean()

5.0

In [73]:
A.std()

2.581988897471611

In [74]:
A.sum(axis=0)

array([12, 15, 18])

In [75]:
A.sum(axis=1)

array([ 6, 15, 24])

In [76]:
A.mean(axis=0)

array([4., 5., 6.])

In [77]:
A.mean(axis=1)

array([2., 5., 8.])

In [78]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [79]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [80]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [81]:
print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


# Broadcasting and VEertorized operations

In [82]:
a = np.array(4)

In [83]:
a

array(4)

In [84]:
a + 10

14

In [85]:
a * 10

40

In [86]:
a

array(4)

In [87]:
a += 100

In [88]:
a

array(104)

In [89]:
l = [0,1,2,3]

In [91]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
b = np.array([10,10,10,10])

In [96]:
a + b

array([10, 11, 12, 13])

In [97]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [98]:
a = np.arange(4)

In [99]:
a

array([0, 1, 2, 3])

In [102]:
a[[True,False,False,True]]

array([0, 3])

In [103]:
a >= 2

array([False, False,  True,  True])

In [104]:
a[a >= 2]

array([2, 3])

In [105]:
a.mean()

1.5

In [106]:
a[a > a.mean()]

array([2, 3])

In [107]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [108]:
a[(a <= 2) | (a % 2 == 0)]

array([0, 1, 2])

In [110]:
A = np.random.randint(100, size=(3,3))

In [111]:
A

array([[61,  0, 11],
       [46, 56, 69],
       [59, 30, 84]])

In [112]:
A > 30

array([[ True, False, False],
       [ True,  True,  True],
       [ True, False,  True]])

# Linear Algebra

In [113]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [114]:
B = np.array([[6,5],[4,3],[2,1]])

In [115]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [116]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [117]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [118]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

## Int, floats

In [120]:
sys.getsizeof(1)

28

In [121]:
sys.getsizeof(10**100)

72

In [122]:
np.dtype(int).itemsize

4

In [123]:
np.dtype(float).itemsize

8

## Lists are even biggerrr

In [124]:
sys.getsizeof([1])

64

In [125]:
np.array([1]).nbytes

4

In [126]:
sys.getsizeof([1,2])

72

In [127]:
sys.getsizeof([1,2,3,4,5])

120

In [128]:
np.array([1,2]).nbytes

8

In [129]:
np.array([1,2,3,4,5]).nbytes

20

## And performance is also importante

In [135]:
l = list(range(100000))

In [141]:
a = np.arange(100000)

In [142]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 991 µs


216474736

In [140]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 29 ms


333328333350000